// <auto-generated />
namespace InterviewSelectionProcess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class note_string_change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(note_string_change));
        
        string IMigrationMetadata.Id
        {
            get { return "201704140543025_note_string_change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
