// <auto-generated />
namespace InterviewSelectionProcess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_NewColumn_ResumePath : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_NewColumn_ResumePath));
        
        string IMigrationMetadata.Id
        {
            get { return "201704121140386_Added_NewColumn_ResumePath"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
